version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    #    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    platform: linux/x86_64
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_app
      - gem-home:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  redoc:
    image: redocly/redoc
    volumes:
      - './open-api/openapi.yml:/usr/share/nginx/html/open_api.yml'
    environment:
      SPEC_URL: open_api.yml
    ports:
      - '8100:80'
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  mysql-data:
    driver: local
  gem-home:
    driver: local

# ネットワーク定義
networks:
  default:
    name: my_app_to_c_network
